const tasksDB = `[{"id":1,"date":"25/4/2021","time":"5:28","place":"272 Southridge Terrace","members":"Renée","category":"sport","task_title":"Langur, hanuman","status"},
{"id":2,"date":"17/12/2020","time":"7:42","place":"4 Northland Drive","members":"Adèle","category":"sport","task_title":"Red-knobbed coot","status"},
{"id":3,"date":"22/11/2020","time":"12:04","place":"7564 Tony Hill","members":"Lyséa","category":"sport","task_title":"Black-cheeked waxbill","status"},
{"id":4,"date":"24/6/2021","time":"1:53","place":"4 Mcguire Road","members":"Kallisté","category":"sport","task_title":"Pine squirrel","status"},
{"id":5,"date":"23/7/2021","time":"13:28","place":"4004 Rutledge Alley","members":"Agnès","category":"sport","task_title":"Australian sea lion","status"},
{"id":6,"date":"17/2/2021","time":"18:54","place":"03127 Sheridan Drive","members":"Eléonore","category":"education","task_title":"Bennett's wallaby","status"},
{"id":7,"date":"4/5/2021","time":"9:00","place":"9400 Ridgeway Hill","members":"Marylène","category":"education","task_title":"Heron, giant","status"},
{"id":8,"date":"7/2/2021","time":"11:02","place":"7 Shelley Drive","members":"Táng","category":"education","task_title":"Bettong, brush-tailed","status"},
{"id":9,"date":"16/5/2021","time":"19:07","place":"5 Bluestem Crossing","members":"Maëlyss","category":"education","task_title":"Francolin, coqui","status"},
{"id":10,"date":"9/9/2020","time":"12:09","place":"67544 Veith Road","members":"Intéressant","category":"duties","task_title":"Lemur, grey mouse","status"},
{"id":11,"date":"11/5/2021","time":"22:29","place":"544 Pine View Point","members":"Åke","category":"duties","task_title":"Tyrant flycatcher","status"},
{"id":12,"date":"22/3/2021","time":"7:13","place":"745 Stephen Road","members":"Maëlle","category":"duties","task_title":"South American meadowlark (unidentified)","status"},
{"id":13,"date":"16/6/2021","time":"2:16","place":"3651 Bluestem Terrace","members":"Personnalisée","category":"duties","task_title":"Bleu, red-cheeked cordon","status"},
{"id":14,"date":"25/9/2020","time":"5:06","place":"74 Comanche Avenue","members":"Gwenaëlle","category":"relax","task_title":"Iguana, common green","status"},
{"id":15,"date":"8/11/2020","time":"4:00","place":"4 Sugar Hill","members":"Léone","category":"relax","task_title":"Common zorro","status"},
{"id":16,"date":"22/8/2021","time":"2:21","place":"93381 Boyd Street","members":"Léa","category":"relax","task_title":"Kangaroo, black-faced","status"},
{"id":17,"date":"6/5/2021","time":"14:37","place":"32494 Pawling Road","members":"Rachèle","category":"relax","task_title":"Tayra"},
{"id":18,"date":"17/11/2020","time":"2:39","place":"8 Riverside Circle","members":"Léonie","category":"relax","task_title":"Silver-backed jackal","status"},
{"id":19,"date":"6/9/2020","time":"15:38","place":"63465 Shelley Road","members":"Rébecca","category":"meeting","task_title":"Langur, gray","status"},
{"id":20,"date":"1/11/2020","time":"2:16","place":"7398 Crowley Center","members":"Måns","category":"meeting","task_title":"American beaver","status"},
{"id":21,"date":"1/7/2021","time":"5:12","place":"01 Packers Alley","members":"Dù","category":"meeting","task_title":"Roadrunner, greater","status"},
{"id":22,"date":"25/7/2021","time":"23:15","place":"397 Armistice Center","members":"Léa","category":"meeting","task_title":"Falcon, peregrine","status"},
{"id":23,"date":"3/6/2021","time":"6:10","place":"49521 Southridge Crossing","members":"Lài","category":"meeting","task_title":"Shrike, crimson-breasted","status"},
{"id":24,"date":"12/11/2020","time":"8:40","place":"51809 Vermont Drive","members":"Måns","category":"appointment","task_title":"Rainbow lory","status"},
{"id":25,"date":"9/7/2021","time":"21:05","place":"731 American Ash Point","members":"Desirée","category":"appointment","task_title":"Helmeted guinea fowl","status"},
{"id":26,"date":"15/12/2020","time":"10:53","place":"60583 Lotheville Drive","members":"Frédérique","category":"appointment","task_title":"Ring-tailed lemur","status"},
{"id":27,"date":"30/8/2021","time":"20:37","place":"6701 Donald Point","members":"Cloé","category":"appointment","task_title":"Purple moorhen","status"},
{"id":28,"date":"13/1/2021","time":"15:49","place":"83501 Redwing Center","members":"Börje","category":"appointment","task_title":"Sifaka, verreaux's","status"},
{"id":29,"date":"14/9/2020","time":"2:26","place":"2 Service Point","members":"Océanne","category":"work","task_title":"Native cat","status"},
{"id":30,"date":"12/3/2021","time":"20:40","place":"9140 Westport Plaza","members":"Solène","category":"work","task_title":"Eagle, tawny","status"},
{"id":31,"date":"12/4/2021","time":"8:40","place":"4 Cardinal Place","members":"Zhì","category":"work","task_title":"Jungle kangaroo","status"},
{"id":32,"date":"25/8/2021","time":"17:14","place":"2756 Mesta Park","members":"Laurélie","category":"work","task_title":"Lapwing (unidentified)","status"},
{"id":33,"date":"5/1/2021","time":"23:20","place":"5065 Marquette Center","members":"Aloïs","category":"work","task_title":"White-eye, pale","status"},
{"id":34,"date":"21/11/2020","time":"4:57","place":"86 Esch Lane","members":"Magdalène","category":"work","task_title":"Water moccasin","status"},
{"id":35,"date":"16/8/2020","time":"2:43","place":"213 Caliangt Court","members":"Annotée","category":"sport","task_title":"Southern hairy-nosed wombat","status"},
{"id":36,"date":"5/4/2021","time":"17:23","place":"76 Fuller Court","members":"Salomé","category":"sport","task_title":"Great egret","status"},
{"id":37,"date":"17/6/2021","time":"18:13","place":"0909 Pleasure Center","members":"Céline","category":"education","task_title":"White-headed vulture","status"},
{"id":38,"date":"23/6/2021","time":"16:27","place":"6 Homewood Drive","members":"Eléonore","category":"education","task_title":"Barbet, levaillant's","status"},
{"id":39,"date":"12/5/2021","time":"11:42","place":"05 Maple Wood Road","members":"Françoise","category":"education","task_title":"Tern, white-winged","status"},
{"id":40,"date":"7/12/2020","time":"0:38","place":"18909 Columbus Place","members":"Loïc","category":"work","task_title":"Swallow (unidentified)","status"},
{"id":41,"date":"19/6/2021","time":"13:16","place":"767 Corben Hill","members":"Kù","category":"work","task_title":"Killer whale","status"},
{"id":42,"date":"4/5/2021","time":"21:21","place":"6128 Twin Pines Court","members":"Irène","category":"work","task_title":"Blue and gold macaw","status"},
{"id":43,"date":"3/8/2020","time":"14:08","place":"1 La Follette Place","members":"Céline","category":"meeting","task_title":"Trumpeter, dark-winged","status"},
{"id":44,"date":"1/1/2021","time":"12:10","place":"202 Acker Junction","members":"Andréanne","category":"meeting","task_title":"Cobra (unidentified)","status"},
{"id":45,"date":"20/11/2020","time":"22:31","place":"38 Roth Avenue","members":"Maéna","category":"meeting","task_title":"Lizard, mexican beaded","status"},
{"id":46,"date":"29/5/2021","time":"3:07","place":"4 Thierer Avenue","members":"Thérèsa","category":"relax","task_title":"African buffalo","status"},
{"id":47,"date":"26/7/2021","time":"8:49","place":"8 Cascade Center","members":"Cécilia","category":"relax","task_title":"Goanna lizard"},
{"id":48,"date":"31/5/2021","time":"7:18","place":"34829 Artisan Alley","members":"Marylène","category":"work","task_title":"Mongoose, banded","status"},
{"id":49,"date":"7/3/2021","time":"1:54","place":"1 Kinsman Alley","members":"Gisèle","category":"work","task_title":"Deer, white-tailed","status"},
{"id":50,"date":"11/1/2021","time":"1:35","place":"93 Ryan Junction","members":"Stévina","category":"duties","task_title":"Cormorant, large","status"}]`;

export const getTasksList = () => JSON.parse(tasksDB);
